### ISSUE TITLE
[Fluxnews] - Signup/Signin with Firebase or Facebook not working

### ISSUE THREAD

**Issue by aldoyh** [inspireui/support#1826]
Hello guys,
I've updated everything and managed to run on the device successfully, but none of the Signup methods nor Sign-in are working, showing the attached SS.

google-services.json also updated and downloaded successfully. 

**I'm still not able to get a stable App for the past 2 months. Please help.**

![Screenshot_1578973794](https://user-images.githubusercontent.com/5215449/72312913-ac315880-369a-11ea-97c6-ceb59544f5e0.png)

This flutter doctor
```

[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57, locale en-US)
    • Flutter version 1.12.13+hotfix.5 at /Users/aldoyh/development/flutter
    • Framework revision 27321ebbad (5 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/aldoyh/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.9.0.beta.2

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • AOSP on IA Emulator • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!
Process finished with exit code 0


```

pubspec.yaml
```

name: whrapp2
description: WE HORSE RACING

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.3.0+8350

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  logs:
    git: https://github.com/pq/logs
  flutter:
    sdk: flutter
  http: 0.12.0+3
  html_unescape: 1.0.1+3
  provider: 3.2.0
  after_layout: 1.0.7+2
  font_awesome_flutter: 8.5.0
  path: 1.6.4
  flutter_facebook_login: 3.0.0
  flutter_account_kit: 0.7.0
  vector_math: 2.0.8
  carousel_pro: 1.0.0
  flutter_widget_from_html_core: 0.2.5
  configurable_expansion_tile: 1.0.0
  timeago: 2.0.22
  share: 0.6.3+5
  validate: 1.7.0
  country_pickers: 1.1.0
  shared_preferences: 0.5.6
  firebase_messaging: 6.0.9
  firebase_analytics: 5.0.9
  transparent_image: 1.0.0
  pull_to_refresh: 1.5.7
  localstorage: 3.0.1+4
  notification_permissions: ^0.4.3
  flare_splash_screen: 3.0.0
  rate_my_app: 0.4.1
  flutter_range_slider: ^1.4.0
  page_indicator: ^0.3.0
  extended_image: 0.6.8
  flutter_screenutil: 0.7.0
  fluttertoast: 3.1.3
  intro_slider: 2.2.8
  url_launcher: 5.4.1
  firebase_core: 0.4.3+1
  firebase_auth: 0.15.3
  firestore_ui: 1.7.2
  flutter_webview_plugin: 0.3.10+1
  connectivity: 0.4.6+1
  random_string: 2.0.1
  google_maps_flutter: 0.5.21+15
  place_picker: 0.9.11
  cached_network_image: 2.0.0-rc.1
  firebase_storage: 3.1.1
  image_picker: 0.6.2+3
  fab_circular_menu: 0.1.3
  uuid: 2.0.4
  uni_links: ^0.2.0
  flutter_staggered_grid_view: ^0.3.0
  device_apps: 1.0.9
  auto_size_text: ^2.1.0
  koukicons: 2.0.2
  lazy_load_scrollview: 1.0.1
  flutter_swiper: 1.1.6
  flutter_widgets: 0.1.7+1
  video_player: 0.10.5
  flutter_spinkit: 4.1.1+1
  percent_indicator: ^2.1.1+1
  flutter_signin_button: ^1.0.0
  youtube_player_flutter: 6.0.3+2
  animated_text_kit: 2.0.0
  wave: 0.0.8
  http_auth: 0.2.7
  firebase_admob: 0.9.0+10
  facebook_audience_network: 0.4.0
  launch_review: 2.0.0
  custom_splash: 0.0.2
  google_fonts: 0.2.0
  google_sign_in: 4.1.1
  apple_sign_in: 0.1.0
  international_phone_input: 1.0.2
  pin_code_fields: 2.3.0+3
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_launcher_icons: ^0.7.4
  flutter_test:
    sdk: flutter

# Run this script to generate the app icon: flutter pub pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true
  assets:
    - lib/common/config.json
    - assets/icons/categories/
    - assets/icons/tabs/
    - assets/icons/profile/
    - assets/icons/payment/
    - assets/images/
    - assets/images/country/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Medium.ttf
        - asset: assets/fonts/Raleway-Bold.ttf
        - asset: assets/fonts/Raleway-Light.ttf
        - asset: assets/fonts/Raleway-Thin.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Light.ttf
        - asset: assets/fonts/Roboto-Thin.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages

```
