### ISSUE TITLE
FluxNews   A problem running the project on Xcode

### ISSUE THREAD

**Issue by haidarsalim** [inspireui/support#3959]
Just completed the Android app on Windows
When I try to run the same project on a Mac, there are a lot of errors
I uploaded the project again and errors appeared at a lower rate
I tried the project on Android Studio and Xcode on Mac

I would like to run the project on xcode to work on the iPhone version

FluxNews Version: 1.4.1
Flutter : v1.17.3

**Open the project on Android Studio on a Mac**
![33](https://user-images.githubusercontent.com/54249914/85947533-fe69eb80-b953-11ea-99ab-39f07abc2040.png)
```

Launching lib/main.dart on haidar in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: 4293TP954W
Running pod install...                                          
Compiler message:
../../../flutter/.pub-cache/hosted/pub.dartlang.org/rate_my_app-0.6.0+2/lib/src/dialogs.dart:272:17: Error: No named parameter with the name 'onRatingChanged'.
                onRatingChanged: (rating) {
                ^^^^^^^^^^^^^^^
../../../flutter/.pub-cache/hosted/pub.dartlang.org/smooth_star_rating-1.1.1/lib/smooth_star_rating.dart:24:3: Context: Found this candidate, but the arguments don't match.
  SmoothStarRating({
  ^^^^^^^^^^^^^^^^
```

**Open the project on Xcode on your Mac**
![222](https://user-images.githubusercontent.com/54249914/85947921-4a1d9480-b956-11ea-8bf7-2664826240ff.png)

**Comment by ameenbadri7** [comment]
to fix this issue please consider updating your `pubspec.yaml` 
  rate_my_app: 0.6.0+2
to 
  rate_my_app: 0.6.0+3

because the package developer has fixed his package update.

and this my `pubspec.yaml` just copy and paste to your `pubspec.yaml` for the fluxnews app.

thank you, sir.

```
name: fstore
description: Mobile commerce app by Flutter

version: 1.4.1+2

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  logs:
    git: https://github.com/pq/logs
  flutter:
    sdk: flutter
  http: 0.12.1
  html_unescape: 1.0.1+3
  provider: 4.1.0
  after_layout: 1.0.7+2
  font_awesome_flutter: 8.8.1
  flutter_facebook_login: 3.0.0
  vector_math: 2.0.8
  configurable_expansion_tile: 1.0.0
  timeago: 2.0.26
  share: 0.6.4+1
  validate: 1.7.0
  shared_preferences: 0.5.7+1
  firebase_messaging: 6.0.13
  firebase_analytics: 5.0.11
  transparent_image: 1.0.0
  pull_to_refresh: 1.5.8
  localstorage: 3.0.2+5
  notification_permissions: 0.4.4
  flare_splash_screen: 3.0.1
  rate_my_app: 0.6.0+3
  page_indicator: ^0.3.0
  intro_slider: 2.2.9
  url_launcher: 5.4.5
  extended_image: 0.7.3-dev
  firebase_core: 0.4.4 # keep these version as there is new issue
  firebase_auth: 0.15.3 # with the latest firebase https://github.com/FirebaseExtended/flutterfire/issues/2084
  firestore_ui: 1.9.1
  flutter_webview_plugin: 0.3.11
  connectivity: 0.4.8+5
  cached_network_image: 2.2.0+1
  image_picker: 0.6.6+1
  fab_circular_menu: 1.0.0
  uuid: 2.0.4
  uni_links: 0.2.0
  flutter_staggered_grid_view: 0.3.0
  auto_size_text: 2.1.0
  flutter_swiper: 1.1.6
  flutter_widgets: 0.1.12
  flutter_spinkit: 4.1.2+1
  percent_indicator: 2.1.3
  animated_text_kit: 2.0.1
  wave: 0.0.8
  http_auth: 0.2.9
  firebase_admob: 0.9.3+2
  facebook_audience_network: 0.5.0
  launch_review: 2.0.0
  custom_splash: 0.0.2
  google_fonts: 1.0.0
  google_sign_in: 4.4.4
  apple_sign_in: 0.1.0
  international_phone_input: 1.0.4
  pin_code_fields: 3.0.0
  onesignal_flutter: 2.4.1
  flutter_widget_from_html: 0.3.3+3
  flutter_statusbarcolor: 0.2.3
  event_bus: 1.1.1
  liquid_swipe: ^1.4.3

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_launcher_icons: 0.7.5
  flutter_test:
    sdk: flutter

# Run this script to generate the app icon: flutter pub pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"

flutter:

  uses-material-design: true
  assets:
    - lib/common/
    - assets/icons/categories/
    - assets/icons/tabs/
    - assets/icons/profile/
    - assets/icons/payment/
    - assets/images/
    - assets/images/country/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Medium.ttf
        - asset: assets/fonts/Raleway-Bold.ttf
        - asset: assets/fonts/Raleway-Light.ttf
        - asset: assets/fonts/Raleway-Thin.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Light.ttf
        - asset: assets/fonts/Roboto-Thin.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
flutter_intl:
  enabled: true
```
