### ISSUE TITLE
open the app and there is no internet, an error appears

### ISSUE THREAD

**Issue by haidarsalim** [inspireui/support#4977]
Fluxstore Version: 1.7.7
Flutter : v1.20.3
You have verified #4807

When I open the app and there is no internet, an error appears
![asset](https://user-images.githubusercontent.com/54249914/92976959-654b6b00-f494-11ea-9ba8-3405423cbebb.png)

2- 
What is the reason for the disappearance of element symbols
![asset](https://user-images.githubusercontent.com/54249914/92977286-4e594880-f495-11ea-8375-903acced1efe.jpg)

**Comment by minhcasi** [comment]
@haidarsalim - pls try this solution https://github.com/inspireui/support/issues/4638

We also fixed it on the latest release 1.7.8 which will be released in the next couple of day - thank you!

**Comment by haidarsalim** [comment]
How about the second question @minhcasi

**Comment by minhcasi** [comment]
Could you try to add these setting 

<img width="651" alt="Screen Shot 2020-09-13 at 09 30 45" src="https://user-images.githubusercontent.com/1459805/93008847-cf066a80-f5a3-11ea-92b2-b447d78c7b8f.png">

```
  fonts:
    - family: MaterialIcons
      fonts:
        - asset: assets/fonts/MaterialIcons.ttf
    - family: Entypo
      fonts:
        - asset: assets/fonts/Entypo.ttf
    - family: FontAwesome
      fonts:
        - asset: assets/fonts/FontAwesome.ttf
    - family: MaterialCommunityIcons
      fonts:
        - asset: assets/fonts/MaterialCommunityIcons.ttf
    - family: Feather
      fonts:
        - asset: assets/fonts/Feather.ttf
```
